-- MySQL Script generated by MySQL Workbench
-- Tue Mar  7 11:14:38 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Data
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Data
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Data` DEFAULT CHARACTER SET utf8 ;
USE `Data` ;

-- -----------------------------------------------------
-- Table `Data`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Data`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `First Name` VARCHAR(45) NOT NULL,
  `Last Name` VARCHAR(45) NULL,
  `picture` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `First Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Data`.`Personal Output`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Data`.`Personal Output` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `required hours` INT GENERATED ALWAYS AS () VIRTUAL,
  `hours logged` INT NULL,
  `Story points` INT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Personal Output_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_Personal Output_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `Data`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Data`.`Team Output`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Data`.`Team Output` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Total required hours` INT NULL,
  `Total hours logged` INT NULL,
  `Amount of team members` INT NULL,
  `Story points team` INT NULL,
  `Average story points per person` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Data`.`Personal Output_copy1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Data`.`Personal Output_copy1` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `required hours` INT GENERATED ALWAYS AS () VIRTUAL,
  `hours logged` INT NULL,
  `Story points` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
